# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         NetAddr-IP-Obfuscate
version:      0.01
version_from: lib/NetAddr/IP/Obfuscate.pm
installdirs:  site
requires:
    File::Slurp:                   0
    NetAddr::IP::Find:             0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
